### ISSUE TITLE
Run 'firmlevelrisk' Python code using a new website link

### ISSUE THREAD

**Issue by woahidmurad** [mschwedeler/firmlevelrisk#1]
Hi Markus,

Thank you so much for developing this Python code. It's really interesting. 

However, when I download the '**Apple (AAPL) Q2 2022 Earnings Call Transcript**' file in the input folder by myself from the Motley Fool website and run the code, it produces an error code '**_IndexError: list index out of range_**'. Could you please let me know how I can solve this problem?

I would like to give you thanks in advance for your cooperation. I look forward to hearing from you soon.

[firmlevelrisk.zip](https://github.com/mschwedeler/firmlevelrisk/files/8935348/firmlevelrisk.zip)

**Comment by mschwedeler** [comment]
@woahidmurad, thank you for catching this! With apologies for the long delay (unfortunately I am unable to provide regular and continuous support for this repo), I have adjusted the code so as to support the current version of the Motley Fool's website.
